binance:
  demo:
    methods:  aggTrades avgPrice depth exchangeInfo historicalTrades klines ping ticker tickers time trades
  trade:
    methods:  balance candles order

cexio:
  demo:
    methods:  convert currency_limits last_price last_prices ohlcv order_book price_stats ticker tickers trade_history
  trade:
    methods:  balance candles last_price last_prices order